name: SKY OS Core Build System

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v4

    - name: Derleme Araçlarını ve GCC Cross-Compiler Kur
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-multilib genisoimage nasm

    - name: Projeyi Derle (Makefile Tetikleme)
      run: |
        make clean
        make

    - name: Çıktıları (Kernel / ISO) Güvenli Artefakt Olarak Sakla
      uses: actions/upload-artifact@v4
      with:
        name: skyos-core-build
        path: |
          *.bin
          *.iso
          kernel.bin
